# Generated by Django 4.2.4 on 2023-09-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_usersocials'),
        ('main', '0004_usercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.ManyToManyField(to='main.certifications')),
                ('projects', models.ManyToManyField(to='main.projects')),
                ('resumes', models.ManyToManyField(to='main.resume')),
                ('skills', models.ManyToManyField(to='main.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('work_experience', models.ManyToManyField(to='main.workexperience')),
            ],
            options={
                'verbose_name_plural': 'User Data',
            },
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
    ]
