# Generated by Django 4.2.4 on 2023-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userdata_delete_usercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
