# Generated by Django 4.2.4 on 2023-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
