# Generated by Django 4.2.4 on 2023-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialmedia',
            name='facebook',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='instagram',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='linkedin',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='twitter',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='youtube',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
    ]
