# Generated by Django 4.2.4 on 2023-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usersocialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialMedia',
        ),
    ]
