# Generated by Django 4.2.4 on 2023-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_socials_userprofile_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social',
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
