# Generated by Django 4.2.4 on 2023-09-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_usersocials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocials',
        ),
    ]
