# Generated by Django 4.2.4 on 2023-09-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_usersocials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocials',
        ),
    ]
